### ISSUE TITLE
Disposing WatsonWSServer doesn't free port

### ISSUE THREAD

**Issue by joreg** [jchristn/WatsonWebsocket#38] opened 2020-10-14 18:46 UTC
hey joel,

we just discovered that disposing the server doesn't free the port. simple to reproduce using these three lines:

    var ws = new WatsonWsServer("127.0.0.1", 6666, false);
    ws.Start();
    ws.Dispose();

are we missing anything in shutting it down?

**Comment by jchristn** [comment] 2020-10-14 18:57
Hi @joreg that should do it.  Are you by chance running on .NET Core on Linux/Mac?  If so we might be running into this (https://github.com/dotnet/runtime/issues/24025) which references this issue (https://github.com/dotnet/corefx/pull/24809)

Could you let me know the OS and framework you are using?

**Comment by jchristn** [comment] 2020-10-14 19:05
By the way, just pushed a new project inside of the repo called ```Test.Dispose```.  I'm testing this on .NET Core and .NET Framework now on Windows.

**Comment by jchristn** [comment] 2020-10-14 19:07
I just noticed my ```Dispose``` method was stopping but not closing.  Amending the code now and adding a ```Test.Dispose``` project to make sure it works as expected.

**Comment by jchristn** [comment] 2020-10-14 19:35
Publishing v2.2.0.3 now.  Added ```Test.Dispose``` project.  Per test 3 within the project it definitely appears that there is some lingering issue with the port after stopping or disposing the server.

**Comment by jchristn** [comment] 2020-10-14 20:09
So it appears I have this partially fixed in v2.2.0.4 (publishing momentarily).  Here are the results from ```Test.Dispose``` using both .NET Framework 4.5.2 and .NET Core App 2.0.
```
C:\Code\Watson\WatsonWebsocket-2.2>test.dispose\bin\debug\net452\test.dispose
Test 1 with server started: True
Test 2 with server stopped: False
Test 3 with server restarted: True
Test 4 with server disposed: False
Test 5 with server started: True

C:\Code\Watson\WatsonWebsocket-2.2>dotnet test.dispose\bin\debug\netcoreapp2.0\test.dispose.dll
Test 1 with server started: True
Test 2 with server stopped: False
Test 3 with server restarted: False
Test 4 with server disposed: False
Test 5 with server started: True
```

Test 3 should be ```true``` in both cases, but it isn't in .NET Core 2.0.

The same is true with .NET Core 3.1
```
C:\Code\Watson\WatsonWebsocket-2.2>dotnet test.dispose\bin\debug\netcoreapp3.1\test.dispose.dll
Test 1 with server started: True
Test 2 with server stopped: False
Test 3 with server restarted: False
Test 4 with server disposed: False
Test 5 with server started: True
```

So I think the issue is the one referenced a few comments ago.

On a side note, I've run into an issue where issuing ```Stop()``` is actually terminating existing connections rather than just stopping the listener from accepting new ones.  

I may have to migrate away from http.sys soon.

NuGet v2.2.0.4: https://www.nuget.org/packages/WatsonWebsocket/2.2.0.4
Commit: https://github.com/jchristn/WatsonWebsocket/commit/7b6f7dbc3a91e78ae90739c3ef264018a1165d36

**Comment by joreg** [comment] 2020-10-15 11:03
perfect. works as expected now. thanks!

**Comment by jchristn** [comment] 2020-10-15 13:26
Glad it's working now @joreg !  I'll close this one and follow the issue referenced above for a later fix.  Cheers, Joel

**Closed by jchristn** 2020-10-15 13:26 UTC
